version: '3.7'

services:
  filer:
    build:
      context: ./filer
    ports:
      - "8005:8005"
    volumes:
      - ./filer/app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME=$BUCKET_NAME
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8005"]
    
  nginx:
    image: nginx:latest
    ports:
      - "8085:8085"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - filer

