name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build

      - name: Tag Docker Image
        run: docker tag filer aminahakhtar/cicd-pipeline:latest

      - name: Push Docker Image
        run: docker push aminahakhtar/cicd-pipeline:latest
