name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Check Docker Images
        run: docker images

      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build

      - name: Tag and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml push
          docker tag filer aminahakhtar/cicd-pipeline:filer
          docker push aminahakhtar/cicd-pipeline:filer
          docker tag nginx aminahakhtar/cicd-pipeline:nginx
          docker push aminahakhtar/cicd-pipeline:nginx